# Generated by Django 4.0.4 on 2022-05-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_customer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='amount',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
    ]
