# Generated by Django 3.2.5 on 2022-05-13 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20220513_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='amount',
            new_name='balance',
        ),
    ]
